# Generated by Django 5.1.7 on 2025-04-08 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_rename_vacancy_vacancy_position_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vacancy",
            name="position",
        ),
    ]
